### ISSUE TITLE
Support for Fulma elements.

### ISSUE THREAD

**Issue by isaacabraham** [MangelMaxime/html-to-elmish#1]
The tool works pretty well already, but it would be great if it was able to provide proper Fulma bindings (if requested). Otherwise, you have to manually do the conversion from the raw divs with styles to the Fulma types.

**Comment by MangelMaxime** [comment]
Since the time this issue has been opened no work has been done in this direction.

So I am closing this issue as I don't think the ratio time investment/benefit is positive.
