### ISSUE TITLE
unable to process HTML closing markup

### ISSUE THREAD

**Issue by DerekLiang** [MangelMaxime/html-to-elmish#13]
The following html incorrectly translated.  It seems that it could not understand the HTML closing markup `/>`. If rewrite it to `></Media>`, it works fine.

```
    <Media>
      <Media left href="#">
        <Media object data-src="holder.js/64x64" alt="Generic placeholder image" />
      </Media>
      <Media body>
        <Media heading>
          Media heading
        </Media>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
      </Media>
    </Media>

```

translate to 

```
media [ ]
    [ media [ HTMLAttr.Custom ("left", "")
              Href "#" ]
        [ media [ HTMLAttr.Custom ("object", "")
                  HTMLAttr.Data ("src", "holder.js/64x64")
                  Alt "Generic placeholder image" ]
            [ ] <----- missing closing bracket ]
          media [ HTMLAttr.Custom ("body", "") ]
            [ media [ HTMLAttr.Custom ("heading", "") ]
                [ str "Media heading" ]
                  str "Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus." ] ]
```

**Comment by MangelMaxime** [comment]
Hello, 
Isn't your code `jsx`?

Because I don't think the `Media` element you use is a valid HTML standard element no?

**Comment by DerekLiang** [comment]
That is right

**Comment by MangelMaxime** [comment]
Then this is why the converter fails.

In order to support void tags, I made a list of them: https://github.com/MangelMaxime/html-to-elmish/blob/master/src/HtmlConverter/Converter.fs#L107-L123

At the time of writing the converter, I didn't find another solution for that. If you have an idea for a fix, I would accept a PR or a prototype for it :)

**Comment by DerekLiang** [comment]
I am wondering if any tag can be self-closing tag. Do you have any reason why we need to white list the self-closing tags?

**Comment by MangelMaxime** [comment]
In html, only the tags in this white list can be self closing otherwise it's not valid HTML.
