### ISSUE TITLE
Support for Feliz

### ISSUE THREAD

**Issue by OnurGumus** [MangelMaxime/html-to-elmish#15]
Support for Feliz would have been very nice.

**Comment by MangelMaxime** [comment]
I don't have time the time for adding it but if someone want to send a PR, I should be able to review it.

**Comment by MangelMaxime** [comment]
Hello @OnurGumus ,

I am kind of limiting the number of project that I am maintaining right now. Both by lack of time and possibilities of using them personnally or at work.

So I don't think, I will add a new renderer in this project in a near future.

Please, feel free to fork the repository and host your own instance of the project if you think it can be useful for others too.
