### ISSUE TITLE
Thoughts on modifying html-to-elmish to support Giraffe View Engine syntax?

### ISSUE THREAD

**Issue by ardave** [MangelMaxime/html-to-elmish#25]
At a very quick glance, it appears as though little more effort might be required than replacing the FSharpNames of HTML attributes to begin with an underscore and lowercase letter.   

https://github.com/ardave/html-to-elmish/blob/html-to-giraffe/src/HtmlConverter/References.fs

There might be tons of added complexity that I'm missing, but I'm running this branch of this fork locally, and find it to be massively valuable for my own work with Giraffe View Engine-rendered views.

**Comment by MangelMaxime** [comment]
Hello @ardave ,

I am kind of limiting the number of project that I am maintaining right now. Both by lack of time and possibilities of using them personnally or at work.

So I don't think, I will add a new renderer in this project in a near future. 

Please, feel free to fork the repository and host an HTML to Giraffe website if you think people will be interested in a tool like that.

In theory, if Giraffe View Engine use the double list representation as standard Fable.React/Elmish then indeed updating the References should be enough.

**Comment by ardave** [comment]
I might do that then if you don't mind:

Fork repo
Replace U/I references from Fable/Elmish to Giraffe
Replace html tag references from Fable/Elmish to Giraffe
Give credit to you wherever seems suitable
Build the code and run it in a separate site on GitHub Pages
...
Profit
