### ISSUE TITLE
Support CSS type providers if a link css is referenced in HTML

### ISSUE THREAD

**Issue by jkone27** [MangelMaxime/html-to-elmish#29]
it would be possible , if a ref stylesheet is referenced in html and it's a public http reacheable website,
to also generate the corresponding typed CSS within the generated HTML :) 

https://github.com/zanaptak/TypedCssClasses

example

original html with boostrap cdn
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="jumbotron text-center">
  <h1>My First Bootstrap Page</h1>
  <p>Resize this responsive page to see the effect!</p> 
</div>
</body>
</html>
```

generated fable code
```fsharp
html [ Lang "en" ]
    [ head [ ]
        [ title [ ]
            [ str "Bootstrap Example" ]
          meta [ CharSet "utf-8" ]
          meta [ Name "viewport"
                 Content "width=device-width, initial-scale=1" ]
          link [ Rel "stylesheet"
                 Href "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" ]
          script [ Src "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" ]
            [ ]
          script [ Src "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" ]
            [ ] ]
      body [ ]
        [ div [ Class $"{Bootstrap.Jumbotron} text-center" ]
            [ h1 [ ]
                [ str "My First Bootstrap Page" ]
              p [ ]
                [ str "Resize this responsive page to see the effect!" ] ] ] ]
```
but probably aslo with Feliz View engine is a bit more elegant as it can really use classes without using explicit untyped strings
https://zaid-ajaj.github.io/Feliz/#/Misc/ViewEngine
```fsharp
[ div [ prop.class [ Bootstrap.Jumbotron prop.textCenter ]
```

plus in a small Css web UI section this could be displayed
```fsharp
open Zanaptak.TypedCssClasses 

type Bootrstap = CssClasses<"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

```

just an idea , this webapp is amazing :)

**Comment by MangelMaxime** [comment]
Hello @jkone27,

really happy that you find this application useful :)

My goal with this application was to make it easier for people to experiment with Elmish. The idea was to support HTML to Elmish. For me, your proposition, is outside of the scope I have in mind for this project.

I also have a limited time so I need to decide where to investigate my free time sorry...

If you think this is something that can be useful to you and other users please feel free to fork this project, mentioning html-to-elmish as an inspiration and host your own version :)
